version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: portulano-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portulano
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3336:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10


  adminer:
    image: adminer
    container_name: portulano-adminer
    restart: always
    ports: 
      - "8080:8080"


  api:
    build: .
    container_name: portulano-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://app:app@db:3306/portulano
      JWT_SECRET: supersecretchangeme
      PORT: 5000
      NODE_ENV: production
    ports:
      - "5000:5000"
    command: sh -c "npx prisma generate && npx prisma migrate deploy && node src/app.js"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

      


volumes:
  dbdata: